'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkyeMusic.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\fbidis\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fnil Segoe UI;}}
        '''{\colortbl ;\red0\green102\blue204;\red51\green153\blue102;}
        '''{\*\generator Riched20 10.0.26100}\viewkind4\uc1 
        '''\pard\cf1\b\f0\fs28\lang9 Skye Music v1.0 What&apos;s New\fs24\par
        '''This upgrade marks a major milestone in SkyeMusic\f1\rquote\f0 s playback architecture \f1\emdash  smoother, smarter, and built to last.\par
        '''\cf0\b0\f0 Released ?? 2025\cf1\b\fs28\par
        '''\par
        '''\cf2\fs24 New Features\par
        '''\cf0\b0 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ChangeLogRT() As String
            Get
                Return ResourceManager.GetString("ChangeLogRT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fnil\fcharset0 Segoe UI;}{\f1\fswiss\fcharset0 Segoe UI;}{\f2\fswiss Segoe UI;}}
        '''{\colortbl ;\red0\green102\blue204;\red51\green153\blue102;}
        '''{\*\generator Riched20 10.0.26100}\viewkind4\uc1 
        '''\pard\cf1\b\f0\fs28\lang9 Skye Music Help\par
        '''\par
        '''\cf2\f1\fs24 Player Shortcuts &amp; Functions\par
        '''\cf0 &lt;Spacebar&gt; \b0 Toggle Play/Pause\par
        '''\b &lt;Ctrl&gt;+&lt;Spacebar&gt; \b0 Stop\par
        '''\b &lt;M&gt; \b0 Toggle Mute\par
        '''\b &lt;Left Arrow&gt;\b0  Fast Reverse\par
        '''\b &lt;Right Arrow&gt; \b [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HelpRT() As String
            Get
                Return ResourceManager.GetString("HelpRT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAbout16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAbout16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAcceptOKGoStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAcceptOKGoStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAdd16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAdd16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAddAll16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAddAll16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAlbumArtSelect() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAlbumArtSelect", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAttributionIcons816() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAttributionIcons816", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAttributionMicrosoft16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAttributionMicrosoft16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageAttributionSyncFusion24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageAttributionSyncFusion24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageChangeLog32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageChangeLog32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageClearRemoveDelete16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageClearRemoveDelete16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCollapse16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCollapse16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageCopy16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageCopy16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageDeleteLog32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageDeleteLog32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEdit16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEdit16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditCopy16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditCopy16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditCut16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditCut16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditDelete16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditDelete16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditPaste16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditPaste16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditProperCase16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditProperCase16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditSelectAll16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditSelectAll16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageEditUndo16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageEditUndo16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageExit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageExit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageExpandAll16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageExpandAll16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageExport16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageExport16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageFullscreen16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageFullscreen16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageGetPath16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageGetPath16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageGlobe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageGlobe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageHelp16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageHelp16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageHistory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageHistory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageImport16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageImport16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageLibrary16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageLibrary16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageLibrary32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageLibrary32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageLog16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageLog16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageLyrics() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageLyrics", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageMoveBottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageMoveBottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageMoveDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageMoveDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageMoveTop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageMoveTop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageMoveUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageMoveUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageMP3Tag16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageMP3Tag16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageOpen16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageOpen16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentFastForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentFastForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentFastReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentFastReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentPause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentPause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentPlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentPlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentPrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentPrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerAccentStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerAccentStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackFastForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackFastForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackFastReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackFastReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackPause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackPause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackPlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackPlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackPrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackPrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerBlackStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerBlackStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerSound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerSound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerSoundMute() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerSoundMute", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhiteFastForward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhiteFastForward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhiteFastReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhiteFastReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhiteNext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhiteNext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhitePause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhitePause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhitePlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhitePlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhitePrevious() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhitePrevious", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePlayerWhiteStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePlayerWhiteStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImagePrune32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImagePrune32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageRating16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageRating16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageRefresh16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageRefresh16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageRefreshLog32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageRefreshLog32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSave32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSave32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSearchFolder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSearchFolder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSettings16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSettings16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageSkyeTag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageSkyeTag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageView() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageView", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageVisualizer16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageVisualizer16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ImageWindows16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ImageWindows16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
